export const UPLOAD_PROJECT_LIST_ACTIO = 'UPLOAD_PROJECT_LIST_ACTION'
export const UPLOAD_PROJECT_DETAIL = 'UPLOAD_PROJECT_DETAIL'

export const UPLOAD_PROJECT_LIST_SAGA = 'UPLOAD_PROJECT_LIST_SAGA'


//MAIN
export const HANDLE_COVER_LIST = 'HANDLE_COVER_LIST'
export const LOAD_COVER_LIST = 'LOAD_COVER_LIST'
export const SEARCH_COVER = 'SEARCH_COVER'
export const HANDLE_PAGE = 'HANDLE_PAGE'
